name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          chmod 777 ./gradlew
          ./gradlew assembleMagiskRelease --build-cache
          ./gradlew --stop

      - name: Prepare upload
        run: |
          mkdir out
          unzip -o module/build/outputs/magisk/Riru-MomoHider.zip -d out

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: riru-momohider
          path: out